name = "dialisis-malaysia"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run pages:build"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = [ "nodejs_compat" ]
