export const TREATMENT_TYPES = [
  "Hemodialisis",
  "Peritoneal Dialisis",
  "Transplant",
  "MRRB",
];

export const SECTOR = [
  "MOH_PRIVATE",
  "MOH",
  "Private",
  "NGO",
  "University",
  "Armed Force",
  "Others",
];

export const STATES = [
  "Semua Negeri / Wilayah",
  "Selangor",
  "Kuala Lumpur",
  "Pulau Pinang",
  "Johor",
  "Perak",
  "Perlis",
  "Putrajaya",
  "Kedah",
  "Kelantan",
  "Melaka",
  "Negeri Sembilan",
  "Pahang",
  "Sabah",
  "Sarawak",
  "Terengganu",
  "Labuan",
];

export const CITIES: Record<string, string[]> = {
  Johor: [
    "Johor Bahru",
    "Tebrau",
    "Pasir Gudang",
    "Bukit Indah",
    "Skudai",
    "Kluang",
    "Batu Pahat",
    "Muar",
    "Ulu Tiram",
    "Senai",
    "Segamat",
    "Kulai",
    "Kota Tinggi",
    "Pontian Kechil",
    "Tangkak",
    "Bukit Bakri",
    "Yong Peng",
    "Pekan Nenas",
    "Labis",
    "Mersing",
    "Simpang Renggam",
    "Parit Raja",
    "Kelapa Sawit",
    "Buloh Kasap",
    "Chaah",
    "Gelang Patah",
  ],
  Kedah: [
    "Sungai Petani",
    "Alor Setar",
    "Kulim",
    "Jitra / Kubang Pasu",
    "Baling",
    "Pendang",
    "Langkawi",
    "Yan",
    "Sik",
    "Kuala Nerang",
    "Pokok Sena",
    "Bandar Baharu",
    "Kuala Kedah",
  ],
  Kelantan: [
    "Kota Bharu",
    "Tanah Merah",
    "Pasir Mas",
    "Gua Musang",
    "Kuala Krai",
    "Tumpat",
    "Bachok",
    "Jeli",
  ],
  Melaka: [
    "Bandaraya Melaka",
    "Bukit Baru",
    "Ayer Keroh",
    "Klebang",
    "Masjid Tanah",
    "Sungai Udang",
    "Batu Berendam",
    "Alor Gajah",
    "Bukit Rambai",
    "Ayer Molek",
    "Bemban",
    "Kuala Sungai Baru",
    "Pulau Sebang",
    "Jasin",
    "Bukit Piatu",
    "Bukit Katil",
    "Bacang",
  ],
  "Negeri Sembilan": [
    "Seremban",
    "Port Dickson",
    "Nilai",
    "Bahau",
    "Tampin",
    "Kuala Pilah",
    "Bandar Sri Jempol",
    "Gemencheh",
    "Gemas",
    "Jelebu",
    "Kuala Klawang",
  ],
  Pahang: [
    "Kuantan",
    "Temerloh",
    "Bentong",
    "Mentakab",
    "Raub",
    "Jerantut",
    "Pekan",
    "Kuala Lipis",
    "Bandar Jengka",
    "Bukit Tinggi",
  ],
  Perak: [
    "Ipoh",
    "Taiping",
    "Sitiawan",
    "Simpang Empat",
    "Teluk Intan",
    "Batu Gajah",
    "Lumut",
    "Kampung Koh",
    "Kuala Kangsar",
    "Sungai Siput Utara",
    "Tapah",
    "Bidor",
    "Parit Buntar",
    "Ayer Tawar",
    "Chemor",
    "Bagan Serai",
    "Tanjung Malim",
    "Lawan Kuda Baharu",
    "Pantai Remis",
    "Kampar",
    "Seri Manjung",
  ],
  Perlis: ["Kangar", "Kuala Perlis"],
  "Pulau Pinang": [
    "Bukit Mertajam",
    "Georgetown",
    "Sungai Ara",
    "Gelugor",
    "Ayer Itam",
    "Butterworth",
    "Perai",
    "Nibong Tebal",
    "Permatang Kucing",
    "Tanjung Tokong",
    "Kepala Batas",
    "Tanjung Bungah",
    "Juru",
    "Bayan Lepas",
  ],
  Sabah: [
    "Kota Kinabalu",
    "Sandakan",
    "Tawau",
    "Lahad Datu",
    "Keningau",
    "Putatan",
    "Donggongon",
    "Semporna",
    "Kudat",
    "Kunak",
    "Papar",
    "Ranau",
    "Beaufort",
    "Kinarut",
    "Kota Belud",
    "Beluran",
    "Nabawan",
    "Pitas",
    "Tambunan",
  ],
  Sarawak: [
    "Kuching",
    "Miri",
    "Sibu",
    "Bintulu",
    "Limbang",
    "Sarikei",
    "Sri Aman",
    "Kapit",
    "Batu Delapan Bazaar",
    "Kota Samarahan",
    "Mukah",
    "Marudi",
  ],
  "Kuala Lumpur": [
    "Cheras",
    "Bukit Bintang",
    "Titiwangsa",
    "Setiawangsa",
    "Wangsa Maju",
    "Batu",
    "Kepong",
    "Segambut",
    "Lembah Pantai",
    "Seputeh",
    "Bandar Tun Razak",
  ],
  Selangor: [
    "Subang Jaya",
    "Klang",
    "Ampang Jaya",
    "Shah Alam",
    "Petaling Jaya",
    "Cheras",
    "Kajang",
    "Selayang Baru",
    "Rawang",
    "Taman Greenwood",
    "Semenyih",
    "Banting",
    "Balakong",
    "Gombak Setia",
    "Kuala Selangor",
    "Serendah",
    "Bukit Beruntung",
    "Pengkalan Kundang",
    "Jenjarom",
    "Cyberjaya",
    "Sungai Besar",
    "Dengkil",
    "Sungai Buloh",
    "Batu Arang",
    "Tanjung Sepat",
    "Kuang",
    "Kuala Kubu Baharu",
    "Batang Berjuntai",
    "Bandar Baru Salak Tinggi",
    "Sekinchan",
    "Sabak",
    "Tanjung Karang",
    "Beranang",
    "Sungai Pelek",
    "Sepang",
    "Telok Panglima Garang",
    "Puchong",
    "Bangi",
  ],
  Terengganu: [
    "Kuala Terengganu",
    "Chukai",
    "Dungun",
    "Kerteh",
    "Kuala Nerus",
    "Kuala Berang",
    "Marang",
    "Paka",
    "Jerteh",
  ],
  "Wilayah Persekutuan": ["Kuala Lumpur", "Labuan", "Putrajaya"],
};

export const NEIGHBORING_STATES: Record<string, string[]> = {
  Selangor: ["Kuala Lumpur", "Putrajaya", "Negeri Sembilan", "Perak", "Pahang"],
  "Kuala Lumpur": ["Selangor", "Putrajaya"],
  Putrajaya: ["Selangor", "Kuala Lumpur"],
  Johor: ["Melaka", "Negeri Sembilan", "Pahang"],
  "Pulau Pinang": ["Kedah", "Perak"],
  Perak: ["Pulau Pinang", "Kedah", "Kelantan", "Pahang", "Selangor"],
  Kedah: ["Perlis", "Pulau Pinang", "Perak"],
  Kelantan: ["Perak", "Pahang", "Terengganu"],
  Terengganu: ["Kelantan", "Pahang"],
  Pahang: ["Selangor", "Negeri Sembilan", "Johor", "Terengganu", "Kelantan", "Perak"],
  "Negeri Sembilan": ["Selangor", "Melaka", "Johor", "Pahang"],
  Melaka: ["Negeri Sembilan", "Johor"],
  Sabah: ["Labuan"],
  Sarawak: [],
  Labuan: ["Sabah"],
  Perlis: ["Kedah"],
};
